### ISSUE TITLE
File/folder does not exist or pls provide comment for link

### ISSUE THREAD

**Issue by bodgergely** [lazyprogrammer/machine_learning_examples#17]
https://github.com/lazyprogrammer/machine_learning_examples/blob/53c89dd7f1efa6f0d6fbba8eee3fc6808511bd42/supervised_class/util.py#L14

**Comment by bodgergely** [comment]
https://www.udemy.com/data-science-supervised-machine-learning-in-python/learn/v4/t/lecture/5642644?start=0 explains where to get the code but would be nice to have a link in the source code too.

**Comment by lazyprogrammer** [comment]
Friend, you are in the repository where the source code is hosted.

**Comment by lazyprogrammer** [comment]
I respond when I feel like it. ;)

> My problem was that the "../large_files/train.csv" was "not found" when I ran this code. My comment above was asking to provide a link for the data repo.

Instructions for getting the data are in the course, thus all that is required is to watch the lectures and follow what they say.

Regards

**Comment by bodgergely** [comment]
I really liked your courses but your attitude now is a huge disappointment. 
Just forget that I ever raised this issue and no need to reply.

**Comment by lazyprogrammer** [comment]
There is no "attitude" here, I am simply stating some basic facts.

It's so basic, you have no reason to be offended by it.

Me: "Instructions for getting the data are in the course" 
You: "How dare you!"

Only those who have too much ego / pride have trouble being told to follow instructions.

Good, productive students never have that problem.

I notice often that poor students say things like "no need to reply." because they are too fragile to handle what I am going to say next, because they know their reasoning is poor and easy to rebut. It's really quite sad.

The real translation is: "No need to reply because my argument has no legs to stand on".

Improve yourself and lower your pride so that you can more easily accept and follow instructions - that is a better strategy.

**Comment by Jian-Qiao** [comment]
> There is no "attitude" here, I am simply stating some basic facts.
> 
> It's so basic, you have no reason to be offended by it.
> 
> Me: "Instructions for getting the data are in the course" You: "How dare you!"
> 
> Only those who have too much ego / pride have trouble being told to follow instructions.
> 
> Good, productive students never have that problem.
> 
> I notice often that poor students say things like "no need to reply." because they are too fragile to handle what I am going to say next, because they know their reasoning is poor and easy to rebut. It's really quite sad.
> 
> The real translation is: "No need to reply because my argument has no legs to stand on".
> 
> Improve yourself and lower your pride so that you can more easily accept and follow instructions - that is a better strategy.

Totally agree with you. It's actually nice of you to reply. I normally just ignore.

**Comment by bodgergely** [comment]
> I respond when I feel like it. ;)
> 
> > My problem was that the "../large_files/train.csv" was "not found" when I ran this code. My comment above was asking to provide a link for the data repo.
> 
> Instructions for getting the data are in the course, thus all that is required is to watch the lectures and follow what they say.
> 
> Regards


Okay, let me point out then explicitely what I was referring to as "attitude":

> Friend, you are in the repository where the source code is hosted.

First of all this a really condescending tone, starting you sentence with "Friend, " is just a great way to show arrogance.

> I respond when I feel like it. ;)

Now this one is very unprofessional. Even if you think that way, there is no need to be so arrogant to even write it down...

Now these are the things where your "attitude" comes from.

> Improve yourself and lower your pride so that you can more easily accept and follow instructions - that is a better strategy.

You should heed your own advice. You don't even realize how condescending you sound.

**Comment by bodgergely** [comment]
> > There is no "attitude" here, I am simply stating some basic facts.
> > It's so basic, you have no reason to be offended by it.
> > Me: "Instructions for getting the data are in the course" You: "How dare you!"
> > Only those who have too much ego / pride have trouble being told to follow instructions.
> > Good, productive students never have that problem.
> > I notice often that poor students say things like "no need to reply." because they are too fragile to handle what I am going to say next, because they know their reasoning is poor and easy to rebut. It's really quite sad.
> > The real translation is: "No need to reply because my argument has no legs to stand on".
> > Improve yourself and lower your pride so that you can more easily accept and follow instructions - that is a better strategy.
> 
> Totally agree with you. It's actually nice of you to reply. I normally just ignore.

Thanks for you input, just keep ignoring.

**Comment by lazyprogrammer** [comment]
> You should heed your own advice. You don't even realize how condescending you sound.

I was casual at first, but changed my tone to match yours - so if there's anything about my tone which you find objectionable - you need only look at who and what I am replying to.

> First of all this a really condescending tone, starting you sentence with "Friend, "

This is just casual talk / banter. Like I said, your ego / pride is affecting you. Your interpretation of neutral words goes to the negative. I'm not responsible for what's in your mind - you are.

If you're so easily offended, that's something you have to deal with yourself.

> Now this one is very unprofessional.

Again, it's just casual talk / banter as described above.

You seem to not realize that is a human to human conversation, not some customer service call where the agent kowtows to the caller and tries their absolute best to assuage their anger.

P.S. You could have just stated that I misread your comment, which would have been true, as it looked like "a link _to_ the source code" rather than "a link _in_ the source code". Though I can't say that would have changed my response, since the point remains that I want students to be able to follow the lectures, and not to provide alternatives to those who are not. That doesn't serve them well, it only serves to encourage their lack of instruction-following. When students follow all the steps outlined in a course, it *helps* them proceed through it more easily. Again, one shouldn't find that offensive, following the course better and more accurately a *good* thing.
