### ISSUE TITLE
best_line_fit.py: Line 39 & 40 should have "+ c" not "-c"

### ISSUE THREAD

**Issue by Garyi113** [lazyprogrammer/machine_learning_examples#24]
Using data points (0,3) (1,4) (2,5)  illustrate the fact that  "c" (the y-intercept) is locked at zero.  Flip the sign and the resultant line tracks the points.

https://github.com/lazyprogrammer/machine_learning_examples/blob/master/best_fit_line.py

**Comment by lazyprogrammer** [comment]
Thanks for your message!

Unfortunately this only works for a subset of particular use cases (when c is positive).

Since c is just a variable it shouldn't matter whether you put +c or -c (if you put -c and the optimal answer is 5, then +c would give the optimal answer -5).

The reason it appears to be "locked" at 0 is because there seems to be implicit constraints built-in by default (e.g. that c >= 0).

In order to see this, you can negate your suggested data points and observe that using +c no longer works.

In any case, this is a super old script (using Python 2!)

Today I would recommend using Scipy's LP solver, which is clearer.

I cover this problem and more in my course: https://deeplearningcourses.com/c/linear-programming-python
