### ISSUE TITLE
Add requirements

### ISSUE THREAD

**Issue by joao-faria** [lazyprogrammer/machine_learning_examples#55]
Hello,

It would be great if you could add the project requirements (requirements.txt, or in some other form). Installing the required libraries is not enough, since we end up not having the correct library versions for running the code.

Thanks

**Comment by lazyprogrammer** [comment]
There's no such thing as correct library because I always add more code examples to the repository over time.

For ex, one file might use TF1 and one file might use TF2, and both files might be in the same folder.

The only way to know for sure is to be a student of my courses.

**Comment by de-code** [comment]
How about adding requirements to the examples directory then?

I don't find it easy to know what version I should be installing. I can't see it in the course description, neither does that seem to be part of the `where to get the code` video.

A `requirements.txt` or similar with the exact version version numbers would help.

This seems to work for the `a2c` example (it doesn't work with TensorFlow 2):

```
gym[atari]==0.17.3
imageio==2.9.0
joblib==0.17.0
opencv-python==4.4.0.46
tensorflow==1.15.4
```

**Comment by lazyprogrammer** [comment]
What do you mean by "examples directory"?

I don't see how your response resolves the issue I posed above, perhaps you can elaborate.

Further, trying to do something like this is not the right approach for my courses.

You are trying to lower the amount of thinking, while I am trying to increase it.

The overarching theme of using requirements files is for the purpose of "automation".

When you are taking my courses, you are not supposed to be automating. You are supposed to be writing code. Building things from scratch. Which library or which version is not fixed.

Please, stop trying to take the approach of "_copy code and run it_", that is not the way.

Watch "How to succeed in this course", "How to code by yourself" (in the FAQ) and "Should you code along?" https://www.youtube.com/watch?v=X4osaNAuJH8

**Comment by de-code** [comment]
> What do you mean by "examples directory"?

For example in this case `rl3/a2c`.

> I don't see how your response resolves the issue I posed above, perhaps you can elaborate.

By adding it to the specific examples directory, `rl3/a2c` in this case, you could have different requirements for each example. Of course you could also add it at a different level.

> Further, trying to do something like this is not the right approach for my courses.
> 
> You are trying to lower the amount of thinking, while I am trying to increase it.
> 
> The overarching theme of using requirements files is for the purpose of "automation".
> 
> When you are taking my courses, you are not supposed to be automating. You are supposed to be writing code. Building things from scratch. Which library or which version is not fixed.
> 
> Please, stop trying to take the approach of "_copy code and run it_", that is not the way.
> 
> Watch "How to succeed in this course", "How to code by yourself" (in the FAQ) and "Should you code along?" https://www.youtube.com/watch?v=X4osaNAuJH8

I appreciate your suggestion.

Interestingly for the `A2C` section you seem to suggest that in this case it's good to build on the baseline code. Of course in the end you suggest to write it from scratch and compare it.

In the end we are all different and how we learn best (or at least I believe that is the case). I think I can learn best if I can see and run something and then break it and take it apart. But in other situations I might write it from scratch, perhaps when I am already more familiar with certain aspects.

**Comment by lazyprogrammer** [comment]
> For example in this case rl3/a2c.

Yes, that's one example, but it doesn't work for all cases.

I appreciate that you probably don't care about the 25+ other courses, but I have to consider everything as a whole.


> Interestingly for the A2C section you seem to suggest that in this case it's good to build on the baseline code.

But here we are talking about something so basic, it doesn't even get up to the level of writing code.

At the very least if one meets the prerequisites to the course, they should be able to recognize which libraries (+versions in the case of TF1 vs TF2) are being used.

If someone tries to run the code and their first comment is "Why doesn't it work with TF2?" then I immediately know they didn't even look at the code.

Looking at and understanding the code would have resolved this. (Not necessarily trying to write it from scratch)

I truly can't fathom how "looking at the code and understanding it" can be too much to ask... especially considering that I've explained them in the lectures.


> In the end we are all different and how we learn best (or at least I believe that is the case).

Sure, but I don't build my courses for edge cases. I build my courses for the majority agreed upon method / "normal way" of learning machine learning.

Again, watch the lectures I presented ("how to code by yourself", "should you code along?" etc.) and if you have any counter-arguments to anything I've said in those lectures, I'd be happy to address them.

Saying, "Everyone learns differently therefore we don't have to listen to you" is a cop-out response and doesn't resolve anything because it doesn't address any of the points specifically. It's a general response that can be used for literally any statement.

"Exercising is good for your health" > "Yeah, but everyone is different. If I exercise, I could die!"

I say sure, you can use whatever approach you like, however, you also have to bear the burden of any difficulties it incurs.
